---
title: "Rесурсы"
subtitle: "полезные ссылки на источники по языку программирования R"
author: "Евгений Матеров"
date: today

date-format: short

lang: ru

format:
  html:
    light: default
    dark:  darkly
editor: visual

toc: true
toc-depth: 2

title-block-banner: true

highlight-style: pygments
---

::: epigraph
*"Wenn du eine weise Antwort verlangst, musst du vernünftig fragen."* --- Johann Wolfgang von Goethe.
:::

# Блоги

| Имя                      | адрес                                    |
|--------------------------|------------------------------------------|
| Julia Silge              | <https://juliasilge.com/>                |
| Emil Hvitfeldt           | <https://www.emilhvitfeldt.com/>         |
| Nathan Yau               | <https://flowingdata.com/>               |
| Dr. Dominic Royé         | <https://dominicroye.github.io/en/>      |
| Milos Popovic            | <https://milospopovic.net/>              |
| Robin Lovelace           | <https://www.robinlovelace.net/>         |
| Thomas Mock              | <https://themockup.blog/>                |
| Taras Kaduk              | <https://taraskaduk.com/>                |
| Masumbuko Semba          | <https://semba-blog.netlify.app/post/>   |
| Data Imaginist           | <https://www.data-imaginist.com/>        |
| June Choe                | <https://yjunechoe.github.io/blog.html>  |
| Programming with R       | <https://www.programmingwithr.com/post/> |
| Stats and R              | <https://statsandr.com/blog/>            |
| Dmitry Shkolnik          | <https://www.dshkol.com/post/>           |
| Josh McCrain             | <http://joshuamccrain.com/>              |
| June Choe                | <https://yjunechoe.github.io/blog.html>  |
| Restless Data            | <https://restlessdata.com.au/>           |
| Alex Cookson             | <https://www.alexcookson.com/>           |
| Ander Fernández Jauregui | <https://anderfernandez.com/en/blog/>    |
| Amit Levinson            | <https://amitlevinson.com/#posts>        |
| Jason Bryer              | <https://bryer.org/post/>                |
| Albert Rapp              | <https://albert-rapp.de/post/>           |
| Harshvardhan             | <https://www.harsh17.in/blog/>           |
| Yuri Vishnevsky          | <https://yuri.is/>                       |
| Katie Press              | <https://kpress.dev/blog/>               |
| Luis D. Verde Arregoitia | <https://luisdva.github.io/posts/>       |
| R and rivers             | <https://ryanpeek.org/>                  |
| mlampros                 | <https://mlampros.github.io/>            |
| r-spatial                | <https://r-spatial.org/>                 |
| RStudio AI Blog          | <https://blogs.rstudio.com/ai/>          |
| mlr-org                  | <https://mlr-org.com/blog.html>          |
| Сергей Мастицкий         | <https://r-analytics.blogspot.com/>      |

# Книги

+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Название                                                                                                       | адрес                                                               |
+================================================================================================================+=====================================================================+
| **Коллекции книг**                                                                                             |                                                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| bookdown                                                                                                       | [https://bookdown.org/](https://bookdown.org/yihui/bookdown/){.uri} |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Big Book of R                                                                                                  | <https://www.bigbookofr.com/index.html>                             |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| **Tidyverse & Tidymodels**                                                                                     |                                                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| R for Data Science                                                                                             | <https://r4ds.had.co.nz/>                                           |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Tidy Modeling with R                                                                                           | <https://www.tmwr.org/>                                             |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Text Mining with R                                                                                             | <https://www.tidytextmining.com/>                                   |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Supervised Machine Learning for Text Analysis in R                                                             | <https://smltar.com/>                                               |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Feature Engineering & Selection                                                                                | <https://bookdown.org/max/FES/>                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Mastering Shiny                                                                                                | <https://mastering-shiny.org/index.html>                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Statistical Inference via Data Science: A ModernDive into R and the Tidyverse                                  | <https://moderndive.com/>                                           |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Tidy Evaluation                                                                                                | <https://tidyeval.tidyverse.org/>                                   |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Functional Programming                                                                                         | <https://dcl-prog.stanford.edu/>                                    |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Data Science. A First Introduction (Tiffany Timbers, Trevor Campbell, and Melissa Lee. Foreword by Roger Peng) | <https://datasciencebook.ca/>                                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| **Геопространственное моделирование**                                                                          |                                                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Spatial Data Science with applications in R                                                                    | <https://keen-swartz-3146c4.netlify.app/>                           |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Introduction to Spatial Data Programming with R                                                                | <http://132.72.155.230:3838/r/index.html>                           |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Geocomputation with R                                                                                          | <https://geocompr.robinlovelace.net/>                               |
|                                                                                                                |                                                                     |
|                                                                                                                | <https://geocompr.github.io/>                                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Geospatial Health Data: Modeling and Visualization with R-INLA and Shiny                                       | <https://www.paulamoraga.com/book-geospatial/index.html>            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Hands-On Spatial Data Science with R                                                                           | <https://spatialanalysis.github.io/handsonspatialdata/>             |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Using Spatial Data with R                                                                                      | <https://cengel.github.io/R-spatial/>                               |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Spatio-Temporal Statistics with R                                                                              | <https://spacetimewithr.org/>                                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| {sits}: Data Analysis and Machine Learning on Earth Observation Data Cubes with Satellite Image Time Series    | <https://e-sensing.github.io/sitsbook/>                             |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Geographic Data Science with Python                                                                            | <https://geographicdata.science/book/intro.html>                    |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Spatial Data Programming with Python                                                                           | <https://geobgu.xyz/py/index.html>                                  |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Awesome Open Geoscience (в основном Python)                                                                    | <https://github.com/softwareunderground/awesome-open-geoscience>    |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| **Книги на английском языке**                                                                                  |                                                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Bayes Rules! An Introduction to Applied Bayesian Modeling                                                      | <https://www.bayesrulesbook.com/>                                   |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Data Science for Economists and Other Animals                                                                  | <https://grantmcdermott.com/ds4e/index.html>                        |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| R Notes for Professionals book                                                                                 | <https://goalkicker.com/RBook/>                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Hands-On Machine Learning with R                                                                               | <https://bradleyboehmke.github.io/HOML/>                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Data Visualization with R (Kabakoff)                                                                           | <https://rkabacoff.github.io/datavis/>                              |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Psych 252: Statistical Methods for Behavioral and Social Sciences                                              | <https://psych252.github.io/psych252book/>                          |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| JavaScript for R                                                                                               | <https://book.javascript-for-r.com/>                                |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| The Epidemiologist R Handbook                                                                                  | <https://epirhandbook.com/en/index.html>                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Reproducible Science for Busy Researchers                                                                      | <https://bookdown.org/alapo/learnr/>                                |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Data Science for Psychologists                                                                                 | <https://bookdown.org/hneth/ds4psy/>                                |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Open Forensic Science in R (судебно-медицинская экспертиза)                                                    | <https://sctyner.github.io/OpenForSciR/>                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| **Книги на русском языке**                                                                                     |                                                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Курс 'Циклы и функционалы в языке R'                                                                           | <https://selesnow.github.io/iterations_in_r/>                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Введение в dplyr 1.0.0                                                                                         | <https://selesnow.github.io/dplyr_1_0_0_course/>                    |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Введение в язык программирования R                                                                             | <https://textbook.rintro.ru/>                                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Визуализация и анализ географических данных на языке R                                                         | <https://tsamsonov.github.io/r-geo-course/>                         |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Пространственная статистика и моделирование на языке R                                                         | <https://tsamsonov.github.io/r-spatstat-course/>                    |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Анализ временных рядов с помощью R                                                                             | <https://ranalytics.github.io/tsa-with-r/>                          |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Классификация, регрессия и другие алгоритмы Data Mining с использованием R                                     | <https://ranalytics.github.io/data-mining/>                         |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Язык R для пользователей Excel                                                                                 | <https://bookdown.org/selesnow/r-for-excel-users/>                  |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+
| Основы статистики для психологов                                                                               | <https://handbook.mathpsy.com/>                                     |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+

# Библиотеки

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| Библиотека                                                                                                                                                                                                                                                                               | адрес                                                                            |
+==========================================================================================================================================================================================================================================================================================+==================================================================================+
| **CAST**: Caret Applications for Spatio-Temporal models                                                                                                                                                                                                                                  | <https://hannameyer.github.io/CAST/index.html>                                   |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Visualization of nearest neighbor distance distributions                                                                                                                                                                                                                               | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **biscale**                                                                                                                                                                                                                                                                              | <https://slu-opengis.github.io/biscale/articles/biscale.html>                    |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Bivarite Mapping with ggplot2                                                                                                                                                                                                                                                          |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **osmextract**                                                                                                                                                                                                                                                                           | <https://github.com/ropensci/osmextract>                                         |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > The goal of osmextract is to make it easier for people to access OpenStreetMap (OSM) data for reproducible research                                                                                                                                                                    | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **stars**: Spatiotemporal Arrays: Raster and Vector Datacubes                                                                                                                                                                                                                            | <https://r-spatial.github.io/stars/index.html>                                   |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Spatiotemporal data (raster maps, time series of satellite images with multiple spectral bands)                                                                                                                                                                                        | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **sftime**                                                                                                                                                                                                                                                                               | <https://r-spatial.org//r/2022/04/12/sftime-1.html>                              |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > The aim of sftime is to extent simple features from the sf package to handle (irregular) spatiotemporal data, such as records on earthquakes, accidents, disease or death cases, lightning strikes, data from weather stations, but also movement data which have further constraints. | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **osmplotr**                                                                                                                                                                                                                                                                             | <https://github.com/ropensci/osmplotr/>                                          |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > R package to produce visually impressive customisable images of OpenStreetMap (OSM) data downloaded internally from the Overpass API.                                                                                                                                                  | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **datadrivencv**                                                                                                                                                                                                                                                                         | | <https://github.com/nstrayer/datadrivencv>                                     |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > The goal of datadrivencv is to ease the burden of maintaining a **CV** by separating the content from the output by treating entries as data. (Красивые **CV**.)                                                                                                                       |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **tabyls**: a tidy, fully-featured approach to counting things                                                                                                                                                                                                                           | | <https://cran.r-project.org/web/packages/janitor/vignettes/tabyls.html>        |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Таблицы с процентовками.                                                                                                                                                                                                                                                               |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **gtsummary**                                                                                                                                                                                                                                                                            | <https://www.danieldsjoberg.com/gtsummary/>                                      |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Provides an elegant and flexible way to create publication-ready analytical and summary tables using the R programming language.                                                                                                                                                       | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **ggdist**                                                                                                                                                                                                                                                                               | <https://mjskay.github.io/ggdist/reference/index.html>                           |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Visualizations of Distributions and Uncertainty                                                                                                                                                                                                                                        | |                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **ggdensity**                                                                                                                                                                                                                                                                            | <https://github.com/jamesotto852/ggdensity>                                      |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > {ggdensity} extends ggplot2 providing more interpretable visualizations of density estimates based on highest density regions (HDRs).                                                                                                                                                  |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **ggblend**                                                                                                                                                                                                                                                                              | <https://mjskay.github.io/ggblend/>                                              |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Visualizations of scatterplot with overlaps                                                                                                                                                                                                                                            |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **vetiver**                                                                                                                                                                                                                                                                              | <https://vetiver.rstudio.com/>                                                   |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > The goal of vetiver is to provide fluent tooling to **version**, **share**, **deploy**, and **monitor** a trained model                                                                                                                                                                |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **xaringanExtra**                                                                                                                                                                                                                                                                        | <https://www.garrickadenbuie.com/blog/xaringanextra-v0.6.0/>                     |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Extras for xaringan                                                                                                                                                                                                                                                                    |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **tidyverts**                                                                                                                                                                                                                                                                            | <https://tidyverts.org/>                                                         |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Tidy tools for time series                                                                                                                                                                                                                                                             |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **data.tree**                                                                                                                                                                                                                                                                            | <https://cran.r-project.org/web/packages/data.tree/vignettes/data.tree.html>     |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Trees                                                                                                                                                                                                                                                                                  |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **TreeDist**                                                                                                                                                                                                                                                                             | <https://cran.r-project.org/web/packages/TreeDist/vignettes/Using-TreeDist.html> |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Calculate tree similarity                                                                                                                                                                                                                                                              |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **ggparty**                                                                                                                                                                                                                                                                              | <https://github.com/martin-borkovec/ggparty>                                     |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > **ggplot2** visualizations for the **partykit** package (trees with regression subplots).                                                                                                                                                                                              |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **ggwrap**                                                                                                                                                                                                                                                                               | <https://github.com/wilkox/ggwrap>                                               |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > {ggwrap} wraps a {ggplot2} plot over multiple rows, to make plots with long x axes easier to read.                                                                                                                                                                                     |                                                                                  |
| >                                                                                                                                                                                                                                                                                        |                                                                                  |
| > Добавляет градиент для временных рядов в {ggplot}.                                                                                                                                                                                                                                     |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **globe4r**                                                                                                                                                                                                                                                                              | <https://globe4r.john-coene.com/index.html>                                      |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Interactive globes for R via [globe.gl.](https://github.com/vasturiano/globe.gl)                                                                                                                                                                                                       |                                                                                  |
| >                                                                                                                                                                                                                                                                                        |                                                                                  |
| > Интерактивный глобус.                                                                                                                                                                                                                                                                  |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **santoku**                                                                                                                                                                                                                                                                              | <https://hughjonesd.github.io/santoku/index.html>                                |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > A versatile cutting tool for R                                                                                                                                                                                                                                                         |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **namedropR**                                                                                                                                                                                                                                                                            | <https://nucleic-acid.github.io/namedropR/index.html>                            |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > provides 'visual citations' containing the metadata of a scientific paper and a 'QR' code.                                                                                                                                                                                             |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **reactablefmtr**                                                                                                                                                                                                                                                                        | <https://kcuilla.github.io/reactablefmtr/index.html>                             |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > The {reactablefmtr} package streamlines and enhances the styling and formatting of tables built with the {reactable} **R** package. The {reactablefmtr} package provides many conditional formatters that are highly customizable and easy to use.                                     |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **tidyterra**                                                                                                                                                                                                                                                                            | <https://dieghernan.github.io/202205_tidyterra/>                                 |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > The goal of {tidyterra} is to provide common methods of the tidyverse packages for objects created with the {terra} package: SpatRaster and SpatVector. It also provides geoms for plotting these objects with {ggplot2}.                                                              |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **sits**                                                                                                                                                                                                                                                                                 | <https://github.com/e-sensing/sits>                                              |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > {sits} is an open source R package for satellite image time series analysis.                                                                                                                                                                                                           |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **crosstable**                                                                                                                                                                                                                                                                           | <https://danchaltiel.github.io/crosstable/>                                      |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > Crosstable is a package centered on a single function, `crosstable`, which easily computes descriptive statistics on datasets. It can use the `tidyverse` syntax and is interfaced with the package `officer` to create automatized reports.                                           |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **stenR**                                                                                                                                                                                                                                                                                | <https://statismike.github.io/stenR/index.html>                                  |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > {stenR} is a package tailored mainly for users and creators of psychological questionnaires, though other social science researchers and survey authors can benefit greatly from it.                                                                                                   |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
| **accessibility**                                                                                                                                                                                                                                                                        | <https://ipeagit.github.io/accessibility/>                                       |
|                                                                                                                                                                                                                                                                                          |                                                                                  |
| > {accessibility} offers a set of fast and convenient functions to calculate multiple transport accessibility measures.                                                                                                                                                                  |                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+

# Полезные ссылки

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Ресурс                                                                                                                                                                                                                                            | Ссылка                                                                                              |
+===================================================================================================================================================================================================================================================+=====================================================================================================+
| Awesome R                                                                                                                                                                                                                                         | <https://github.com/qinwf/awesome-R>                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| **awesome-r-dataviz**                                                                                                                                                                                                                             | <https://krzjoa.github.io/awesome-r-dataviz/>                                                       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Color Brewer                                                                                                                                                                                                                                      | <https://colorbrewer2.org/>                                                                         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Carbon                                                                                                                                                                                                                                            | <https://carbon.now.sh/>                                                                            |
|                                                                                                                                                                                                                                                   |                                                                                                     |
| > Create and share beautiful images of your source code.                                                                                                                                                                                          |                                                                                                     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| How to customize Mac terminal with open source tools (iTerm2, Oh My Zsh, and Powerlevel10k)                                                                                                                                                       | <https://opensource.com/article/20/8/iterm2-zsh>                                                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Spatial Data Science with R (terra & raster)                                                                                                                                                                                                      | <https://rspatial.org/terra>                                                                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Accessing elevation data in R with the elevatr package (растровые карты высот)                                                                                                                                                                    | <https://cran.r-project.org/web/packages/elevatr/vignettes/introduction_to_elevatr.html>            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Terrain Tiles (растровые карты)                                                                                                                                                                                                                   | <https://registry.opendata.aws/terrain-tiles/>                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Tidy storm trajectories                                                                                                                                                                                                                           | <https://r-spatial.org/r/2017/08/28/nest.html>                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Introduction to Geospatial Raster and Vector Data with R: References                                                                                                                                                                              | <https://uw-madison-datascience.github.io/r-raster-vector-geospatial/reference/>                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Mapping Raster Data in the Tidyverse                                                                                                                                                                                                              | <https://rpubs.com/timothyfraser/mapping_raster_data_in_the_tidyverse>                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Accelerate your plots with ggforce                                                                                                                                                                                                                | <https://rviews.rstudio.com/2019/09/19/intro-to-ggforce/>                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Experimenting with machine learning in R with tidymodels and the Kaggle titanic dataset                                                                                                                                                           | <https://oliviergimenez.github.io/blog/learning-machine-learning/>                                  |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Creating presence-absence rasters in 2022                                                                                                                                                                                                         | <https://amywhiteheadresearch.wordpress.com/2022/04/19/creating-presence-absences-rasters-in-2022/> |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Binary image classification using Keras in R: Using CT scans to predict patients with Covid                                                                                                                                                       | <https://oliviergimenez.github.io/blog/image-classif/>                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| R Markdown Tips, Tricks, and Shortcuts                                                                                                                                                                                                            | <https://www.dataquest.io/blog/r-markdown-tips-tricks-and-shortcuts/>                               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| VSCode vs RStudio --- Worth the switch?                                                                                                                                                                                                           | <https://karatsidhu.medium.com/vscode-vs-rstudio-worth-the-switch-7a4415fc3275>                     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Getting started with Python using R and reticulate                                                                                                                                                                                                | <https://rtichoke.netlify.app/post/getting_started_with_reticulate/>                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Top 50 ggplot2 Visualizations                                                                                                                                                                                                                     | <http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html>                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Nature Geoscience                                                                                                                                                                                                                                 | <https://www.nature.com/ngeo/research-articles>                                                     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Using R for Spatial Data Analysis                                                                                                                                                                                                                 | <https://michaeldorman.github.io/R-Spatial-Workshop-at-CBS-2021/main.html#Setup:_sample_data>       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Questionnaires and Surveys: Analyses with R                                                                                                                                                                                                       | <https://slcladal.github.io/surveys.html>                                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| GitHub Actions for the R language                                                                                                                                                                                                                 | <https://github.com/r-lib/actions>                                                                  |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| SlidesGo: Free Google Slides and PowerPoint templates to boost your presentations                                                                                                                                                                 | <https://slidesgo.com/>                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| MyST - Markedly Structured Text                                                                                                                                                                                                                   | <https://myst-parser.readthedocs.io/en/latest/index.html>                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Python and R Tips                                                                                                                                                                                                                                 | <https://cmdlinetips.com/>                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| OSRM Travel-time calculation with R and data visualization with Observable                                                                                                                                                                        | <https://rysebaert.github.io/climbing_paris/>                                                       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| LearningApps.org создан для поддержки обучения и преподавания с помощью небольших общедоступных интерактивных модулей (далее - упражнений). Данные упражнения создаются онлайн и в дальнейшем могут быть использованы в образовательном процессе. | <https://learningapps.org/>                                                                         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Regular Expressions                                                                                                                                                                                                                               | <https://regex101.com/>                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Анализ текстов в R                                                                                                                                                                                                                                | <https://agricolamz.github.io/2020.11.01_appcogn_text_analysis/>                                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Психология: 39 исследований человеческого восприятия                                                                                                                                                                                              | <https://awdee.ru/psychology-39-studies-of-human-perception/>                                       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| Данные о природных пожарах в вашей Веб ГИС (NextGIS)                                                                                                                                                                                              | <https://nextgis.ru/blog/ngw_fires/>                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+

# Видеоблоги

+--------------------------------------------------------+-------------------------------------------------------------------+
| Ресурс                                                 | Ссылка                                                            |
+========================================================+===================================================================+
| David Robinson Tidy Tuesday                            | <https://www.youtube.com/user/safe4democracy>                     |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Julia Silge                                            | <https://www.youtube.com/JuliaSilge/>                             |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Andrew Couch                                           | <https://www.youtube.com/c/AndrewCouch>                           |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Kelsey Gonzalez                                        | <https://www.youtube.com/c/KelseyGonzalez>                        |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Shiny Developer Series                                 | <https://www.youtube.com/c/ShinyDeveloperSeries>                  |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Rstudio                                                | <https://www.youtube.com/c/RStudioPBC>                            |
+--------------------------------------------------------+-------------------------------------------------------------------+
| R4DS Online Learning Community                         | <https://www.youtube.com/c/R4DSOnlineLearningCommunity>           |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Spatial network analysis with the {sfnetworks} package | <https://youtu.be/2cCXUYgEtGw>                                    |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Основы программирования для географов                  | <https://www.youtube.com/channel/UC99_v_T0CTEsYiY2O6YsvOA>        |
+--------------------------------------------------------+-------------------------------------------------------------------+
| Artem Golubnichy                                       | <https://www.youtube.com/channel/UCLIphG_4eXZqf4C6VBg8pUw/videos> |
+--------------------------------------------------------+-------------------------------------------------------------------+

# Курсы

+------------------------------------------------------------------+--------------------------------------------------------------------+
| Курс                                                             | адрес                                                              |
+==================================================================+====================================================================+
| Supervised Machine Learning: Case Studies in R                   | <https://supervised-ml-course.netlify.app/>                        |
+------------------------------------------------------------------+--------------------------------------------------------------------+
| Coding for Data Analysis with R                                  | <https://github.com/gabors-data-analysis/da-coding-rstats#sources> |
+------------------------------------------------------------------+--------------------------------------------------------------------+
| Мастер-класс от ИНИД "Как построить карту, используя R и QGIS"   | <https://github.com/Irrrkah/russia_population_mk>                  |
+------------------------------------------------------------------+--------------------------------------------------------------------+
| Data science for economists                                      | <https://github.com/uo-ec607/lectures>                             |
+------------------------------------------------------------------+--------------------------------------------------------------------+
| Course materials for: Geospatial Data Science                    | <https://github.com/mszell/geospatialdatascience>                  |
+------------------------------------------------------------------+--------------------------------------------------------------------+
| Geospatial Analysis and Representation for Data Science (Python) | <https://napo.github.io/geospatial_course_unitn/lessons/>          |
+------------------------------------------------------------------+--------------------------------------------------------------------+
| purrr tutorial                                                   | <https://jennybc.github.io/purrr-tutorial/>                        |
+------------------------------------------------------------------+--------------------------------------------------------------------+

# Наборы данных и хакатоны

+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Название                                                        | адрес                                                                                                         |
+=================================================================+===============================================================================================================+
| NoFireWithAI: прогнозирование степени пожароопасности           | <https://github.com/sberbank-ai/no_fire_with_ai_aij2021>                                                      |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| NoFloodWithAI: прогнозирование паводков на реке Амур            | <https://github.com/ai-forever/no_flood_with_ai_aij2020>                                                      |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| ИНИД                                                            | <https://data-in.ru/>                                                                                         |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Карта ДТП                                                       | <https://dtp-stat.ru/opendata>                                                                                |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| rspatialdata (раздел Tutorials)                                 | <https://rspatialdata.github.io/index.html>                                                                   |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Emergency DataHack                                              | <https://emergencydatahack.ru/>                                                                               |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Winning a Flood-Forecasting Hackathon with Hydrology and AutoML | <https://towardsdatascience.com/winning-a-flood-forecasting-hackathon-with-hydrology-and-automl-156a8a7a4ede> |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Tidy Tuesday                                                    | <https://github.com/rfordatascience/tidytuesday>                                                              |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| MakeoverMonday                                                  | <https://www.makeovermonday.co.uk/data/>                                                                      |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Dataset Search                                                  | <https://datasetsearch.research.google.com/>                                                                  |
+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+

# Shiny Examples

+------------------------------------+----------------------------------------------+
| Название                           | адрес                                        |
+====================================+==============================================+
| Hastings Half-Marathon             | <https://matt-dray.github.io/hastings-half/> |
+------------------------------------+----------------------------------------------+
| Unravel data manipulation examples | <https://nshrest.shinyapps.io/datawhats/>    |
+------------------------------------+----------------------------------------------+

# Презентации

+-------------------------------------------------+--------------------------------------------------------------------------------------+
| Название                                        | адрес                                                                                |
+=================================================+======================================================================================+
| Designing ggplots                               | <https://designing-ggplots.netlify.app/#1>                                           |
+-------------------------------------------------+--------------------------------------------------------------------------------------+
| Applied Machine Learnring (Max Kuhn)            | <https://rstudio-conf-2020.github.io/applied-ml/README.html>                         |
+-------------------------------------------------+--------------------------------------------------------------------------------------+
| Tidymodels, Virtually (Alison Hill)             | <https://www.apreshill.com/blog/2020-06-how-i-taught-tidymodels-virtually/>          |
+-------------------------------------------------+--------------------------------------------------------------------------------------+
| Introduction to {gt} + {gtsummary} Packages     | <http://www.danieldsjoberg.com/gt-and-gtsummary-presentation/>                       |
+-------------------------------------------------+--------------------------------------------------------------------------------------+
| Introduction to the Tidyverse data manipulation | <https://oliviergimenez.github.io/reproducible-science-workshop/slides/3_dplyr.html> |
+-------------------------------------------------+--------------------------------------------------------------------------------------+
| CÉDRIC SCHERER \[Selected Presentations\]       | <https://www.cedricscherer.com/top/about/#presentations>                             |
+-------------------------------------------------+--------------------------------------------------------------------------------------+
| Quarto as Reveal.js Slides                      | <https://jeremy-allen.github.io/quarto-demo/#/>                                      |
+-------------------------------------------------+--------------------------------------------------------------------------------------+

# Meetups

+---------------------+----------------------------------------------------------------------------+
| Название            | адрес                                                                      |
+=====================+============================================================================+
| R meetups (Russian) | <https://meetups.rintro.ru/>                                               |
+---------------------+----------------------------------------------------------------------------+
| R-Ladies Freiburg   | <https://github.com/rladies/meetup-presentations_freiburg>                 |
|                     |                                                                            |
|                     | <https://www.youtube.com/playlist?list=PLPwprT5wdzX7NVDl4oYQ7c2_6ox0_1fyr> |
+---------------------+----------------------------------------------------------------------------+
